/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppMarketsRouteImport } from './routes/_app.markets'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppPositionsRouteImport } from './routes/_app.positions'
import { Route as AppRiskControlsRouteImport } from './routes/_app.risk-controls'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppStrategiesIndexRouteImport } from './routes/_app.strategies.index'
import { Route as AppStrategiesIdRouteImport } from './routes/_app.strategies.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPositionsRoute = AppPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskControlsRoute = AppRiskControlsRouteImport.update({
  id: '/risk-controls',
  path: '/risk-controls',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStrategiesIndexRoute = AppStrategiesIndexRouteImport.update({
  id: '/strategies/',
  path: '/strategies/',
  getParentRoute: () => AppRoute,
} as any)
const AppStrategiesIdRoute = AppStrategiesIdRouteImport.update({
  id: '/strategies/$id',
  path: '/strategies/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/markets': typeof AppMarketsRoute
  '/orders': typeof AppOrdersRoute
  '/positions': typeof AppPositionsRoute
  '/risk-controls': typeof AppRiskControlsRoute
  '/settings': typeof AppSettingsRoute
  '/strategies/$id': typeof AppStrategiesIdRoute
  '/strategies/': typeof AppStrategiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/markets': typeof AppMarketsRoute
  '/orders': typeof AppOrdersRoute
  '/positions': typeof AppPositionsRoute
  '/risk-controls': typeof AppRiskControlsRoute
  '/settings': typeof AppSettingsRoute
  '/strategies/$id': typeof AppStrategiesIdRoute
  '/strategies': typeof AppStrategiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/connect': typeof ConnectRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/markets': typeof AppMarketsRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/positions': typeof AppPositionsRoute
  '/_app/risk-controls': typeof AppRiskControlsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/strategies/$id': typeof AppStrategiesIdRoute
  '/_app/strategies/': typeof AppStrategiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/markets'
    | '/orders'
    | '/positions'
    | '/risk-controls'
    | '/settings'
    | '/strategies/$id'
    | '/strategies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/markets'
    | '/orders'
    | '/positions'
    | '/risk-controls'
    | '/settings'
    | '/strategies/$id'
    | '/strategies'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/connect'
    | '/login'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/markets'
    | '/_app/orders'
    | '/_app/positions'
    | '/_app/risk-controls'
    | '/_app/settings'
    | '/_app/strategies/$id'
    | '/_app/strategies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/markets': {
      id: '/_app/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/positions': {
      id: '/_app/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AppPositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk-controls': {
      id: '/_app/risk-controls'
      path: '/risk-controls'
      fullPath: '/risk-controls'
      preLoaderRoute: typeof AppRiskControlsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/strategies/': {
      id: '/_app/strategies/'
      path: '/strategies'
      fullPath: '/strategies/'
      preLoaderRoute: typeof AppStrategiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/strategies/$id': {
      id: '/_app/strategies/$id'
      path: '/strategies/$id'
      fullPath: '/strategies/$id'
      preLoaderRoute: typeof AppStrategiesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppMarketsRoute: typeof AppMarketsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPositionsRoute: typeof AppPositionsRoute
  AppRiskControlsRoute: typeof AppRiskControlsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStrategiesIdRoute: typeof AppStrategiesIdRoute
  AppStrategiesIndexRoute: typeof AppStrategiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppMarketsRoute: AppMarketsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPositionsRoute: AppPositionsRoute,
  AppRiskControlsRoute: AppRiskControlsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStrategiesIdRoute: AppStrategiesIdRoute,
  AppStrategiesIndexRoute: AppStrategiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConnectRoute: ConnectRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
